apps/funcionarios/urls.py
from django.conf.urls import url
from django.urls import path
from .views import (
    FuncionariosList,
    FuncionarioEdit,
    FuncionarioDelete,
    FuncionarioNovo,
    Pdf,
    PdfDebug
)
from .views import pdf_reportlab

urlpatterns = [
    path('funcionarios', FuncionariosList.as_view(), name='list_funcionarios'),
    path('novo/', FuncionarioNovo.as_view(), name='create_funcionario'),
    path('editar/<int:pk>/', FuncionarioEdit.as_view(), name='update_funcionario'),
    path('delete/<int:pk>/', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('pdf-reportlab', pdf_reportlab, name='pdf_reportlab'),
    path('relatorio_funcionario_html', Pdf.as_view(), name='relatorio_funcionario_html'),
    path('relatorio_funcionario_html_debug', PdfDebug.as_view(), name='relatorio_funcionario_html_debug')
]

gestao_rh/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

from gestao_rh import settings

urlpatterns = [
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('documento/', include('apps.documentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    #path('favicon.ico',RedirectView.as_view(url='/static/images/favicon.ico')),
    path('accounts/', include('django.contrib.auth.urls')),
] # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/documentos/models.py
from django.db import models
from apps.funcionarios.models import Funcionario
from django.shortcuts import reverse

class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos/')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa
from django.db.models import Sum

class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)
    de_ferias = models.BooleanField(default=False)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    @property
    def total_horas_extra(self):
        total = self.registrohoraextra_set.filter(
            utilizada=False).aggregate(
            Sum('horas'))['horas__sum']
        return total or 0

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario

class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def get_absolute_url(self):
        #return reverse('update_hora_extra', args=[self.id])
        return reverse('update_funcionario', args=[self.funcionario.id])

    def __str__(self):
        return self.motivo

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    ListView,
    UpdateView,
    DeleteView,
    CreateView, TemplateView
)
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas

from django.http import HttpResponse
from django.template.loader import  get_template
import xhtml2pdf.pisa as pisa

from .models import Funcionario

class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')

class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        #username = funcionario.nome
        funcionario.empresa=self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)


def pdf_reportlab(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment'; filename="mypdf-pdf"

    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(10, 810, "Relatório de Funcionarios")

    funcionarios = Funcionario.objects.all()

    palavras = ['palavra1', 'palavra2', 'palavra3']

    y = 790
    str_ = 'Nome: %s | Total Hora Extra %.2f'
    p.drawString(0, 800, '_' * 150)

    for funcionario in funcionarios:
        p.drawString(10, y, str_ % (funcionario.nome, funcionario.total_horas_extra))
        y -= 40

    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response
    #buffer.seek(0)
    #return FileResponse(buffer, as_attachment=True, filename='hello.pdf')


class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type='application/pdf')
            response['Content-Disposition'] = 'attachment;filename=%s.pdf' % filename
            return response
        else:
            return HttpResponse("Error Rendering PDF", status=400)


class Pdf(View):

    def get(self, request):
        params = {
            'today': 'Variavel today',
            'sales': 'Variavel sales',
            'request': request,
        }
        return Render.render('funcionarios/relatorio.html', params, 'myfile')

class PdfDebug(TemplateView):
    template_name = 'funcionarios/relatorio.html'

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
  Exclusão de Fucionário
<form method="post">
    {% csrf_token %}
    <h1> Você esta certo que quer deletar {{ obj }}</h1>

    {{ form }}

    <button type="submit" class="btn btn-danger">Confirma a Exclusão</button>
</form>
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}]

{{ object.id }}

<form method="post">
    {% csrf_token %}

    {{ form|bootstrap }}

    <button type="submit" class="btn btn-main">Salvar</button>
</form>

<br>
<h2>Documentos</h2>
<ul>
    {% for documento in object.documento_set.all %}
        <a href="{{ documento.arquivo.url }}">{{ documento }}</a> <br>
    {% endfor %}
</ul>
<a href="{% url 'create_document' object.id %}" class="btn btn-success">
    Adicionar Documento</a>

<br>

<h2>Banco de Horas</h2>
<ul>
    {% for registro_hora in object.registrohoraextra_set.all %}
        <li>
            <a href="{% url 'update_hora_extra' registro_hora.id %}">
            {{ registro_hora.motivo }} | {{ registro_hora.horas }}<br>
        </a>
        </li>
    {% endfor %}
</ul>

<h3>Total de Horas Extras: {{ object.total_horas_extra }}</h3>
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
    List
<br>
    {% for funcionario in object_list %}
        <a href="{% url 'update_funcionario' funcionario.id %}">{{ funcionario }}</a>
        <a href="{% url 'delete_funcionario' funcionario.id %}"> Deletar</a> <br>
    {% endfor %}

    <a href="{% url 'create_funcionario' %}" class="btn btn-info"> Novo </a>
    <a href="{% url 'relatorio_funcionario_html' %}" class="btn btn-info"> Gerar Relatorio Html </a>
    <a href="{% url 'relatorio_funcionario_html_debug' %}" class="btn btn-danger"> Gerar Relatorio Html Debug </a>
{% endblock %}

apps/funcionarios/templates/funcionarios/relatorio.html
{% extends 'base.html' %}}

{% block staticcss %}
    <style>
        .teste { color: red; }
    </style>
{% endblock %}

{% block main %}
    <h1 class="teste">Meu relatorio</h1>
    <h2>{{ sales }}</h2>
    <a href="{% url 'relatorio_funcionario_html' %}" class="btn btn-info"> Gerar Relatorio Html </a>
{% endblock %}